rm(list=ls())
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(plyranges)
source("~/Desktop/PalmTrees/Analysis/Code/hasOverlap.R")
source("~/Desktop/PalmTrees/Analysis/Code/CustomThemes.R")
load("~/Desktop/PalmTrees/Analysis/WorkspaceData/TxVsRepeats.Rdata") # This has been generated by sourcing OverlapTxAndRepeats.R

# We add a column that indicates if a tx is part of a Union palm tree
tx_repeats$isInUnionPT = tx_repeats$BPID %in% unique(txptinfo$BPID)

# We only consider the Union SV callset for this analysis 
union_tx = tx_repeats %>% filter(SVCaller == "Union") %>% distinct()

union_tx = union_tx %>% 
  left_join(union_wgscircles %>% dplyr::select(BPID, CircleGenomeClass)) %>% 
  mutate(WGSCircles_CircleGenomeClass = as.character(CircleGenomeClass)) %>% 
  dplyr::select(-CircleGenomeClass) %>% 
  left_join(union_circleseq %>% dplyr::select(BPID, CircleGenomeClass)) %>%
  mutate(CircleSeqCircles_CircleGenomeClass = as.character(CircleGenomeClass)) %>% 
  dplyr::select(-CircleGenomeClass)

# We separate rearrangements in their breakends 
union_bkp = 
  data.frame(
    "Chr" = c(union_tx$ChrA, union_tx$ChrB),
    "Pos" = c(union_tx$PosA, union_tx$PosB),
    "BPID" = c(union_tx$BPID, union_tx$BPID),
    "Sample" = c(union_tx$Sample, union_tx$Sample),
    "Repeat" = c(union_tx$RepeatA, union_tx$RepeatB),
    "RepeatClass" = c(union_tx$RepeatClassA, union_tx$RepeatClassB),
    "isInUnionPT" = c(union_tx$isInUnionPT, union_tx$isInUnionPT),
    "WGSCircles_CircleGenomeClass" = c(union_tx$WGSCircles_CircleGenomeClass, union_tx$WGSCircles_CircleGenomeClass),
    "CircleSeqCircles_CircleGenomeClass" = c(union_tx$CircleSeqCircles_CircleGenomeClass, union_tx$CircleSeqCircles_CircleGenomeClass)
  ) %>% as_tibble() %>%
  mutate(SampleChrPos = paste0(Sample, "_", Chr, ":", Pos))

# Just sanity-checking a while...
nrow(union_bkp) 
union_bkp = distinct(union_bkp)
nrow(union_bkp) 
length(unique(union_bkp$BPID)) 
length(unique(union_bkp$SampleChrPos)) # ---> some breakpoints belong to several rearrangements
union_bkp  = union_bkp %>% dplyr::select(-BPID)
union_bkp = distinct(union_bkp)
nrow(union_bkp) 

# First Impression of the Data ---------------------------------------------

# This is the number of breakpoints (each rearrangment has two of them).
# We need it for later.
ntx_all_samples = 
  union_bkp %>%
  dplyr::select(SampleChrPos) %>% 
  distinct() %>%
  nrow()

ntx_all_samples_circleseqcircles = 
  union_bkp %>%
  filter(!is.na(CircleSeqCircles_CircleGenomeClass)) %>% 
  dplyr::select(SampleChrPos) %>% 
  distinct() %>%
  nrow()


# Bar plot of % Breakpoints by repeat class
union_bkp %>%
  filter(!is.na(RepeatClass)) %>%
  group_by(RepeatClass) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  mutate(RepeatClass = forcats::fct_reorder(RepeatClass, -n)) %>% 
  ggplot(aes(x = RepeatClass, y = 100*n/ntx_all_samples)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_RepeatClass.pdf", height=3, width=5)

# Bar plot of % Breakpoints by repeat class
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  group_by(Repeat) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  mutate(Repeat = forcats::fct_reorder(Repeat, -n)) %>% 
  filter(n/ntx_all_samples > 0.005) %>% 
  ggplot(aes(x = Repeat, y = 100*n/ntx_all_samples)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_Repeat.pdf", height=3, width=8)

# Bar plot of % Breakpoints by repeat and Palm tree
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  group_by(Repeat,isInUnionPT) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(Repeat) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples > 0.005) %>% 
  mutate(Repeat = forcats::fct_reorder(Repeat, -Overall)) %>% 
  ggplot(aes(x = Repeat, y = 100*n/ntx_all_samples, color=isInUnionPT, fill=isInUnionPT)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_Repeat_byIsInUnionPT.pdf", height=3, width=8)

# Bar plot of % Breakpoints by repeat class and Palm tree
union_bkp %>%
  filter(!is.na(RepeatClass)) %>%
  group_by(RepeatClass,isInUnionPT) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(RepeatClass) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples > 0.005) %>% 
  mutate(RepeatClass = forcats::fct_reorder(RepeatClass, -Overall)) %>% 
  ggplot(aes(x = RepeatClass, y = 100*n/ntx_all_samples, color=isInUnionPT, fill=isInUnionPT)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_RepeatClass_byIsInUnionPT.pdf", height=3, width=8)

# Bar plot of % Breakpoints by repeat and WGSCircles CircleGenomeClass
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  group_by(Repeat,WGSCircles_CircleGenomeClass) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(Repeat) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples > 0.005) %>% 
  mutate(Repeat = forcats::fct_reorder(Repeat, -Overall)) %>% 
  ggplot(aes(x = Repeat, y = 100*n/ntx_all_samples, color=WGSCircles_CircleGenomeClass, fill=WGSCircles_CircleGenomeClass)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_Repeat_WGSCircles_CircleGenomeClass.pdf", height=3, width=8)

# Bar plot of % Breakpoints by repeat class and WGSCircles CircleGenomeClass
union_bkp %>%
  filter(!is.na(RepeatClass)) %>%
  group_by(RepeatClass,WGSCircles_CircleGenomeClass) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(RepeatClass) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples > 0.005) %>% 
  mutate(RepeatClass = forcats::fct_reorder(RepeatClass, -Overall)) %>% 
  ggplot(aes(x = RepeatClass, y = 100*n/ntx_all_samples, color=WGSCircles_CircleGenomeClass, fill=WGSCircles_CircleGenomeClass)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_RepeatClass_WGSCircles_CircleGenomeClass.pdf", height=3, width=8)


# Bar plot of % Breakpoints by repeat and WGSCircles CircleGenomeClass

union_bkp %>%
  filter(!is.na(Repeat), !is.na(CircleSeqCircles_CircleGenomeClass)) %>%
  group_by(Repeat,CircleSeqCircles_CircleGenomeClass) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(Repeat) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples_circleseqcircles > 0.01) %>% 
  mutate(Repeat = forcats::fct_reorder(Repeat, -Overall)) %>% 
  ggplot(aes(x = Repeat, y = 100*n/ntx_all_samples_circleseqcircles, color=CircleSeqCircles_CircleGenomeClass, fill=CircleSeqCircles_CircleGenomeClass)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_Repeat_CircleSeqCircles_CircleGenomeClass.pdf", height=3, width=8)

# Bar plot of % Breakpoints by repeat class and WGSCircles CircleGenoemClass
union_bkp %>%
  filter(!is.na(Repeat), !is.na(CircleSeqCircles_CircleGenomeClass)) %>%
  group_by(RepeatClass,CircleSeqCircles_CircleGenomeClass) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  group_by(RepeatClass) %>% 
  mutate(Overall = sum(n)) %>% 
  ungroup() %>% 
  filter(Overall/ntx_all_samples_circleseqcircles > 0.005) %>% 
  mutate(RepeatClass = forcats::fct_reorder(RepeatClass, -Overall)) %>% 
  ggplot(aes(x = RepeatClass, y = 100*n/ntx_all_samples_circleseqcircles, color=CircleSeqCircles_CircleGenomeClass, fill=CircleSeqCircles_CircleGenomeClass)) +
  geom_col() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_RepeatClass_CircleSeqCircles_CircleGenomeClass.pdf", height=3, width=8)



# Rank plot of % Breakpoints by repeat 
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  group_by(Repeat) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ggplot(aes(x=rank(100*n/ntx_all_samples, ties.method="random"), y = 100*n/ntx_all_samples)) +
  geom_point() +
  geom_text_repel(aes(label=ifelse(100*n/ntx_all_samples>1, as.character(Repeat), NA))) +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_Repeat_RankPlot.pdf", height=4, width=4)

# Rank plot of % Breakpoints by repeat but only for Alu
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  filter(grepl("Alu", Repeat)) %>%
  group_by(Repeat) %>%
  summarise(n = n_distinct(SampleChrPos)) %>%
  ggplot(aes(x=rank(100*n/ntx_all_samples, ties.method="random"), y = 100*n/ntx_all_samples)) +
  geom_point() +
  geom_text_repel(aes(label=ifelse(100*n/ntx_all_samples>1, as.character(Repeat), NA))) +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Union_Repeat_OnlyAlu.pdf", height=4, width=4)

# This is the number of breakpoints in the Alu class
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  filter(grepl("Alu", Repeat)) %>%
  summarise(ntx_all_samples = ntx_all_samples,
            tx_in_alu = n_distinct(SampleChrPos),
            tx_in_alu_percent = n_distinct(SampleChrPos) / ntx_all_samples) 

# This is the number of breakpoints by different Alus
union_bkp %>%
  filter(!is.na(Repeat)) %>%
  filter(grepl("Alu", Repeat)) %>%
  group_by(Repeat) %>% 
  summarise(ntx_all_samples = ntx_all_samples,
            tx_in_alu = n_distinct(SampleChrPos),
            tx_in_alu_percent = n_distinct(SampleChrPos) / ntx_all_samples) %>%  
  arrange(desc(tx_in_alu))

# Rank plot of % Breakpoints by repeat and sample
union_bkp %>%
  full_join(union_bkp %>% group_by(Sample) %>% summarise(NumberOfBkpPerSample = n_distinct(SampleChrPos))) %>% 
  filter(!is.na(Repeat)) %>%
  group_by(Repeat, RepeatClass, Sample) %>%
  summarise(AbsoluteNumberOfBkp = n_distinct(SampleChrPos),
            RelativeNumberOfBkp = n_distinct(SampleChrPos)/NumberOfBkpPerSample[[1]]) %>%
  ungroup() %>% 
  ggplot(aes(x = Repeat, y = RelativeNumberOfBkp, size=AbsoluteNumberOfBkp)) +
  geom_jitter() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1()

# Rank plot of % Breakpoints by repeat class and sample
union_bkp %>%
  full_join(union_bkp %>% group_by(Sample) %>% summarise(NumberOfBkpPerSample = n_distinct(SampleChrPos))) %>% 
  filter(!is.na(Repeat)) %>%
  group_by(RepeatClass, Sample) %>%
  summarise(AbsoluteNumberOfBkp = n_distinct(SampleChrPos),
            RelativeNumberOfBkp = n_distinct(SampleChrPos)/NumberOfBkpPerSample[[1]]) %>%
  ungroup() %>% 
  ggplot(aes(x = RepeatClass, y = RelativeNumberOfBkp, size=AbsoluteNumberOfBkp)) +
  geom_jitter() +
  ylab("Breakpoints [%]") + 
  xlab("") + 
  theme_kons1() 



# Getting Repeat Statistics for Reference Genome ---------------------------------------------

broad_whitelist = read.table("~/Desktop/PalmTrees/Data/BroadIntervals/b37-wgs_calling_regions.v1.interval_list_toHg19_chr_MinusBlckLst.txt", sep="\t", header=F)
broad_whitelist$ID = paste0("ID_", as.character(1:nrow(broad_whitelist)))
broad_whitelist$Length = broad_whitelist$V3-broad_whitelist$V2 # Length of all whitelisted intervals
broad_whitelist_gr = makeGRangesFromDataFrame(broad_whitelist, seqnames.field = "V1", start.field="V2", end.field="V3", strand.field="V4", keep.extra.columns = T)
broad_whitelist_SumLength = sum(broad_whitelist$Length)

# Use only repeats that overlap with whitelist
repeats_whitelisted_gr  = repeats_gr %>%
  join_overlap_intersect(broad_whitelist_gr)

# length repeats_gr: 5,232,244
# sum length repeats_gr: 1,442,811,701
# length repeats_whitelisted_gr: 5,177,846 (losing 2% of repetitive regions)
# sum length repeats_whitelisted_gr: 1,415,907,216 (losing 2% of repetitive region length)

# Overlap of (whitlisted) genome by repeat 
repeats_percentgenome = repeats_whitelisted_gr %>%
  mutate(Length=end-start) %>% 
  group_by(Repeat, Class) %>%
  summarise(PercentGenome = 100*sum(Length)/broad_whitelist_SumLength) %>%
  as_tibble()
repeats_percentgenome$Repeat = reorder(repeats_percentgenome$Repeat, -repeats_percentgenome$PercentGenome)

# Plot genome coverage for the most common repeats (more than 0.5% of genome spanned)
repeats_percentgenome %>%
  filter(PercentGenome > 0.5) %>% 
  ggplot(aes(x = Repeat, y=PercentGenome)) +
  geom_col() + 
  theme_kons1() + 
  xlab("") + 
  ylab("Whitelisted Genome Covered [%]") +
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/RepeatsGenomeCoverage.pdf", height=4, width=4)

# Overlap of (whitlisted) genome by repeat class
repeatclass_percentgenome = repeats_whitelisted_gr %>%
  mutate(Length=end-start) %>% 
  group_by(Class) %>%
  summarise(PercentGenome = 100*sum(Length)/broad_whitelist_SumLength) %>%
  as_tibble()
repeatclass_percentgenome$Class = reorder(repeatclass_percentgenome$Class, -repeatclass_percentgenome$PercentGenome)

# Plot genome coverage for the most common repeat classes (more than 0.5% of genome spanned)
repeatclass_percentgenome %>%
  filter(PercentGenome > 0.5) %>% 
  ggplot(aes(x = Class, y=PercentGenome)) +
  geom_col() + 
  theme_kons1() + 
  xlab("") + 
  ylab("Whitelisted Genome Covered [%]") +
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/RepeatClassGenomeCoverage.pdf", height=4, width=4)


# compare genome-wide frequency of abundance with number tx in repeats ---------------------------------------------

# this is just a gr that contains the breakpoints
union_bkp_gr = makeGRangesFromDataFrame(union_bkp, seqnames.field = "Chr", start.field = "Pos", end.field = "Pos", ignore.strand = T,  keep.extra.columns = T)

# get only those tx that are in whitelisted regions of the genome
union_bkp_gr_whitelisted = union_bkp_gr %>%
  join_overlap_intersect(broad_whitelist_gr) 
length(union_bkp_gr) 
length(union_bkp_gr_whitelisted) #(lose very few rearrangements)

# This is the number of breakpoints (each rearrangment has two of them).
# We need it for later.
ntx_all_samples_whitelisted = 
  union_bkp_gr_whitelisted %>%
  as.data.frame() %>% 
  dplyr::select(SampleChrPos) %>% 
  distinct() %>%
  nrow()

# Union BKP Repeats over Random

union_bkp_repeats_fc_over_random = union_bkp_gr %>%
  group_by(Repeat) %>%
  summarise(nTx = n_distinct(SampleChrPos)) %>% as_tibble() %>% 
  ungroup() %>% 
  mutate(PercentTx = 100 * nTx / length(union_bkp_gr)) %>% 
  left_join(repeats_percentgenome) %>%
  mutate(FC = PercentTx / PercentGenome)

union_bkp_repeats_fc_over_random$pval = 
  mapply(
    function(x,n,p) binom.test(x,n,p, alternative="two.sided")$p.value,
    union_bkp_repeats_fc_over_random$nTx,
    length(union_bkp_gr),
    union_bkp_repeats_fc_over_random$PercentGenome/100)

union_bkp_repeats_fc_over_random$pval = 
  p.adjust(union_bkp_repeats_fc_over_random$pval, method="BH")

union_bkp_repeats_fc_over_random =
  union_bkp_repeats_fc_over_random %>% 
  mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red")))

# Volcano-type plot
union_bkp_repeats_fc_over_random %>%
  ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
  scale_x_log10() +
  geom_point(size=0.5) +
  geom_text_repel(label=ifelse(union_bkp_repeats_fc_over_random$VolcanoColor != "grey" & (-log10(union_bkp_repeats_fc_over_random$pval)>10 | log10(union_bkp_repeats_fc_over_random$FC)>2.5), union_bkp_repeats_fc_over_random$Repeat, NA), 
                  size=2.5) +
  scale_color_manual(values=c("grey" = "gray95", "blue"="steelblue", "red"="firebrick2"))+
  theme_kons1() +
  xlab("Fold Change") + 
  ylab("-log10(p-value)") +
  guides(color=F) +
  ggtitle("Union \n All Rearrangements vs. Random") + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/UnionAllTx_Vs_Genome_Repeat_Volcano.pdf", height=5, width=5)


# Union BKP Repeat Classes over Random 
union_bkp_repeatclasses_fc_over_random = union_bkp_gr %>%
  group_by(RepeatClass) %>%
  summarise(nTx = n_distinct(SampleChrPos)) %>% as_tibble() %>% 
  ungroup() %>% 
  mutate(PercentTx = 100 * nTx / length(union_bkp_gr)) %>% 
  left_join(repeatclass_percentgenome %>% mutate(RepeatClass = Class)) %>%
  mutate(FC = PercentTx / PercentGenome)

union_bkp_repeatclasses_fc_over_random$pval = 
  mapply(
    function(x,n,p) binom.test(x,n,p, alternative="two.sided")$p.value,
    union_bkp_repeatclasses_fc_over_random$nTx,
    length(union_bkp_gr),
    union_bkp_repeatclasses_fc_over_random$PercentGenome/100)

union_bkp_repeatclasses_fc_over_random$pval = 
  p.adjust(union_bkp_repeatclasses_fc_over_random$pval, method="BH")

union_bkp_repeatclasses_fc_over_random =
  union_bkp_repeatclasses_fc_over_random %>% 
  mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red")))

union_bkp_repeatclasses_fc_over_random %>%
  ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
  scale_x_log10() +
  geom_point(size=0.5) +
  #geom_text_repel(label=ifelse(union_bkp_repeatclasses_fc_over_random$VolcanoColor != "grey" & (-log10(union_bkp_repeatclasses_fc_over_random$pval)>10 | log10(union_bkp_repeatclasses_fc_over_random$FC)>2.5), union_bkp_repeatclasses_fc_over_random$RepeatClass, NA), 
  #                size=2.75) +
  geom_text_repel(label=ifelse(union_bkp_repeatclasses_fc_over_random$VolcanoColor != "grey", union_bkp_repeatclasses_fc_over_random$RepeatClass, NA), 
                  size=2.5) +
  scale_color_manual(values=c("grey" = "gray95", "blue"="steelblue", "red"="firebrick2"))+
  theme_kons1() +
  xlab("Fold Change") + 
  ylab("-log10(p-value)") +
  guides(color=F) + 
  ggtitle("Union \n All Rearrangements vs. Random") + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/UnionAllTx_Vs_Genome_RepeatClass_Volcano.pdf", height=5, width=5)

# compare repeat frequency for pt vs non-pt ----------------------------------------------

union_bkp_repeats_pt_vs_nonpt = 
  union_bkp_gr %>% as_tibble() %>% 
  mutate(isInUnionPT = droplevels(as.factor(ifelse(isInUnionPT, "PalmTreeTx", "NonPalmTreeTx")))) %>% 
  mutate(Repeat=droplevels(forcats::fct_explicit_na(Repeat, na_level="NoRepeat"))) %>% 
  group_by(Repeat, isInUnionPT) %>% 
  summarise(nTx = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  tidyr::complete(Repeat, isInUnionPT, fill=list(nTx=0)) %>% 
  spread(isInUnionPT, nTx) %>% 
  dplyr::rename(ThisRepeat_NonPalmTreeTx = NonPalmTreeTx,
                ThisRepeat_PalmTreeTx = PalmTreeTx) %>% 
  mutate(Other_NonPalmTreeTx = sum(ThisRepeat_NonPalmTreeTx)-ThisRepeat_NonPalmTreeTx,
         Other_PalmTreeTx = sum(ThisRepeat_PalmTreeTx)-ThisRepeat_PalmTreeTx) 

# calculate and adjust p value 
col.fisher.test = function(AB,AnonB,nonAB,nonAnonB){
  contingency_matrix = matrix(c(AB,AnonB,nonAB,nonAnonB), ncol=2, byrow=T)
  ft = fisher.test(contingency_matrix, alternative="two.sided")
  return(ft$p.value)
}
union_bkp_repeats_pt_vs_nonpt$pval = 
  mapply(col.fisher.test, 
         union_bkp_repeats_pt_vs_nonpt$ThisRepeat_PalmTreeTx, union_bkp_repeats_pt_vs_nonpt$Other_PalmTreeTx,
         union_bkp_repeats_pt_vs_nonpt$ThisRepeat_NonPalmTreeTx, union_bkp_repeats_pt_vs_nonpt$Other_NonPalmTreeTx)
union_bkp_repeats_pt_vs_nonpt$pval = 
  p.adjust(union_bkp_repeats_pt_vs_nonpt$pval, method="BH")

# calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
union_bkp_repeats_pt_vs_nonpt = union_bkp_repeats_pt_vs_nonpt %>% 
  mutate(FC = (0.00001 + (1+ThisRepeat_PalmTreeTx) / (1+sum(ThisRepeat_PalmTreeTx))) / (0.00001 + (1+ThisRepeat_NonPalmTreeTx) / (1+sum(ThisRepeat_NonPalmTreeTx))))

union_bkp_repeats_pt_vs_nonpt = union_bkp_repeats_pt_vs_nonpt %>%
  mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 

union_bkp_repeats_pt_vs_nonpt %>% 
  ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
  scale_x_log10() +
  geom_point(size=0.5) +
  geom_text_repel(label=ifelse(union_bkp_repeats_pt_vs_nonpt$VolcanoColor != "grey", union_bkp_repeats_pt_vs_nonpt$Repeat, NA), 
                  size=2.5) +
  scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
  theme_kons1() +
  xlab(paste0("Fold Change \n Enriched in Non Palm Tree Tx <> Enriched in Palm Tree Tx")) + 
  ylab("-log10(p-value)") +
  guides(color=F) + 
  geom_vline(xintercept=1, linetype="dashed") + 
  geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
  ggtitle("Repeat Enrichment \n Palm Tree Tx vs. Non Palm Tree Tx") + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_PalmTreeVsNonPalmTree_Repeat_Volcano.pdf", height=4, width=5)


# compare repeat class frequency for pt vs non-pt ----------------------------------------------

union_bkp_repeats_pt_vs_nonpt = 
  union_bkp_gr %>% as_tibble() %>% 
  mutate(isInUnionPT = droplevels(as.factor(ifelse(isInUnionPT, "PalmTreeTx", "NonPalmTreeTx")))) %>% 
  mutate(RepeatClass=droplevels(forcats::fct_explicit_na(RepeatClass, na_level="NoRepeat"))) %>% 
  group_by(RepeatClass, isInUnionPT) %>% 
  summarise(nTx = n_distinct(SampleChrPos)) %>%
  ungroup() %>% 
  tidyr::complete(RepeatClass, isInUnionPT, fill=list(nTx=0)) %>% 
  spread(isInUnionPT, nTx) %>% 
  dplyr::rename(ThisRepeat_NonPalmTreeTx = NonPalmTreeTx,
                ThisRepeat_PalmTreeTx = PalmTreeTx) %>% 
  mutate(Other_NonPalmTreeTx = sum(ThisRepeat_NonPalmTreeTx)-ThisRepeat_NonPalmTreeTx,
         Other_PalmTreeTx = sum(ThisRepeat_PalmTreeTx)-ThisRepeat_PalmTreeTx) 


# calculate and adjust p value 
col.fisher.test = function(AB,AnonB,nonAB,nonAnonB){
  contingency_matrix = matrix(c(AB,AnonB,nonAB,nonAnonB), ncol=2, byrow=T)
  ft = fisher.test(contingency_matrix, alternative="two.sided")
  return(ft$p.value)
}
union_bkp_repeats_pt_vs_nonpt$pval = 
  mapply(col.fisher.test, 
         union_bkp_repeats_pt_vs_nonpt$ThisRepeat_PalmTreeTx, union_bkp_repeats_pt_vs_nonpt$Other_PalmTreeTx,
         union_bkp_repeats_pt_vs_nonpt$ThisRepeat_NonPalmTreeTx, union_bkp_repeats_pt_vs_nonpt$Other_NonPalmTreeTx)
union_bkp_repeats_pt_vs_nonpt$pval = 
  p.adjust(union_bkp_repeats_pt_vs_nonpt$pval, method="BH")

# calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
union_bkp_repeats_pt_vs_nonpt = union_bkp_repeats_pt_vs_nonpt %>% 
  mutate(FC = (0.00001 + (1+ThisRepeat_PalmTreeTx) / (1+sum(ThisRepeat_PalmTreeTx))) / (0.00001 + (1+ThisRepeat_NonPalmTreeTx) / (1+sum(ThisRepeat_NonPalmTreeTx))))

union_bkp_repeats_pt_vs_nonpt = union_bkp_repeats_pt_vs_nonpt %>%
  mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 

union_bkp_repeats_pt_vs_nonpt %>% 
  ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
  scale_x_log10() +
  geom_point(size=0.5) +
  geom_text_repel(label=ifelse(union_bkp_repeats_pt_vs_nonpt$VolcanoColor != "grey", union_bkp_repeats_pt_vs_nonpt$RepeatClass, NA), 
                  size=2.5) +
  scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
  theme_kons1() +
  xlab(paste0("Fold Change \n Enriched in Non Palm Tree Tx <> Enriched in Palm Tree Tx")) + 
  ylab("-log10(p-value)") +
  guides(color=F) + 
  geom_vline(xintercept=1, linetype="dashed") + 
  geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
  ggtitle("Repeat Class \n Enrichment Palm Tree Tx vs. Non Palm Tree Tx") + 
  ggsave("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_PalmTreeVsNonPalmTree_RepeatClass_Volcano.pdf", height=4, width=5)


# compare repeat class frequency for WGSCircles ----------------------------------------------

circlegenomeclasses = c("circle-circle", "circle-genome", "genome-genome")

for (thiscirclegenomeclass in circlegenomeclasses){

  ## Repeat
  
  union_bkp_repeats_circlegenomeclass_vs_rest = 
    union_bkp_gr %>% as_tibble() %>% 
    filter(!is.na(WGSCircles_CircleGenomeClass)) %>% 
    mutate(isInThisCircleGenomeClass = as.factor(ifelse(WGSCircles_CircleGenomeClass == thiscirclegenomeclass, "this_circle_genome_class", "not_this_circle_genome_class"))) %>% 
    mutate(Repeat=droplevels(forcats::fct_explicit_na(Repeat, na_level="NoRepeat"))) %>% 
    group_by(Repeat, isInThisCircleGenomeClass) %>% 
    summarise(nTx = n_distinct(SampleChrPos)) %>%
    ungroup() %>% 
    tidyr::complete(Repeat, isInThisCircleGenomeClass, fill=list(nTx=0)) %>% 
    spread(isInThisCircleGenomeClass, nTx) %>% 
    dplyr::rename(ThisRepeat_NotThisCircGenClass = not_this_circle_genome_class,
                  ThisRepeat_ThisCircGenClass = this_circle_genome_class) %>% 
    mutate(Other_NotThisCircGenClass = sum(ThisRepeat_NotThisCircGenClass)-ThisRepeat_NotThisCircGenClass,
           Other_ThisCircGenClass = sum(ThisRepeat_ThisCircGenClass)-ThisRepeat_ThisCircGenClass) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    mapply(col.fisher.test, 
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_ThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_ThisCircGenClass,
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_NotThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_NotThisCircGenClass)
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    p.adjust(union_bkp_repeats_circlegenomeclass_vs_rest$pval, method="BH")
  
  # calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    mutate(FC = (0.00001 + (1+ThisRepeat_ThisCircGenClass) / (1+sum(ThisRepeat_ThisCircGenClass))) / (0.00001 + (1+ThisRepeat_NotThisCircGenClass) / (1+sum(ThisRepeat_NotThisCircGenClass))))
  
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>%
    mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
    scale_x_log10() +
    geom_point(size=0.5) +
    geom_text_repel(label=ifelse(union_bkp_repeats_circlegenomeclass_vs_rest$VolcanoColor != "grey", as.character(union_bkp_repeats_circlegenomeclass_vs_rest$Repeat), NA), 
                    size=2.5) +
    scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
    theme_kons1() +
    xlab(paste0("Fold Change \n Depleted <> Enriched")) + 
    ylab("-log10(p-value)") +
    guides(color=F) + 
    geom_vline(xintercept=1, linetype="dashed") + 
    geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
    ggtitle(paste0("Repeat \n Enrichment in ", thiscirclegenomeclass, " (WGS Circles)")) + 
    ggsave(paste0("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_WGSCircles_", thiscirclegenomeclass, "_vs_other_Repeat_Volcano.pdf"), height=4, width=5)
  
  
  ## Repeat Class
  
  union_bkp_repeats_circlegenomeclass_vs_rest = 
    union_bkp_gr %>% as_tibble() %>% 
    filter(!is.na(WGSCircles_CircleGenomeClass)) %>% 
    mutate(isInThisCircleGenomeClass = as.factor(ifelse(WGSCircles_CircleGenomeClass == thiscirclegenomeclass, "this_circle_genome_class", "not_this_circle_genome_class"))) %>% 
    mutate(RepeatClass=droplevels(forcats::fct_explicit_na(RepeatClass, na_level="NoRepeat"))) %>% 
    group_by(RepeatClass, isInThisCircleGenomeClass) %>% 
    summarise(nTx = n_distinct(SampleChrPos)) %>%
    ungroup() %>% 
    tidyr::complete(RepeatClass, isInThisCircleGenomeClass, fill=list(nTx=0)) %>% 
    spread(isInThisCircleGenomeClass, nTx) %>% 
    dplyr::rename(ThisRepeat_NotThisCircGenClass = not_this_circle_genome_class,
                  ThisRepeat_ThisCircGenClass = this_circle_genome_class) %>% 
    mutate(Other_NotThisCircGenClass = sum(ThisRepeat_NotThisCircGenClass)-ThisRepeat_NotThisCircGenClass,
           Other_ThisCircGenClass = sum(ThisRepeat_ThisCircGenClass)-ThisRepeat_ThisCircGenClass) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    mapply(col.fisher.test, 
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_ThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_ThisCircGenClass,
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_NotThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_NotThisCircGenClass)
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    p.adjust(union_bkp_repeats_circlegenomeclass_vs_rest$pval, method="BH")
  
  # calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    mutate(FC = (0.00001 + (1+ThisRepeat_ThisCircGenClass) / (1+sum(ThisRepeat_ThisCircGenClass))) / (0.00001 + (1+ThisRepeat_NotThisCircGenClass) / (1+sum(ThisRepeat_NotThisCircGenClass))))
  
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>%
    mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
    scale_x_log10() +
    geom_point(size=0.5) +
    geom_text_repel(label=ifelse(union_bkp_repeats_circlegenomeclass_vs_rest$VolcanoColor != "grey", as.character(union_bkp_repeats_circlegenomeclass_vs_rest$RepeatClass), NA), 
                    size=2.5) +
    scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
    theme_kons1() +
    xlab(paste0("Fold Change \n Depleted <> Enriched")) + 
    ylab("-log10(p-value)") +
    guides(color=F) + 
    geom_vline(xintercept=1, linetype="dashed") + 
    geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
    ggtitle(paste0("Repeat Class \n Enrichment in ", thiscirclegenomeclass, " (WGS Circles)")) + 
    ggsave(paste0("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_WGSCircles_", thiscirclegenomeclass, "_vs_other_RepeatClass_Volcano.pdf"), height=4, width=5)
}


# compare repeat class frequency for Circle-seq circles ----------------------------------------------

circlegenomeclasses = c("circle-circle", "circle-genome", "genome-genome")

for (thiscirclegenomeclass in circlegenomeclasses){
  
  ## Repeat
  
  union_bkp_repeats_circlegenomeclass_vs_rest = 
    union_bkp_gr %>% as_tibble() %>% 
    filter(!is.na(CircleSeqCircles_CircleGenomeClass)) %>% 
    mutate(isInThisCircleGenomeClass = as.factor(ifelse(CircleSeqCircles_CircleGenomeClass == thiscirclegenomeclass, "this_circle_genome_class", "not_this_circle_genome_class"))) %>% 
    mutate(Repeat=droplevels(forcats::fct_explicit_na(Repeat, na_level="NoRepeat"))) %>% 
    group_by(Repeat, isInThisCircleGenomeClass) %>% 
    summarise(nTx = n_distinct(SampleChrPos)) %>%
    ungroup() %>% 
    tidyr::complete(Repeat, isInThisCircleGenomeClass, fill=list(nTx=0)) %>% 
    spread(isInThisCircleGenomeClass, nTx) %>% 
    dplyr::rename(ThisRepeat_NotThisCircGenClass = not_this_circle_genome_class,
                  ThisRepeat_ThisCircGenClass = this_circle_genome_class) %>% 
    mutate(Other_NotThisCircGenClass = sum(ThisRepeat_NotThisCircGenClass)-ThisRepeat_NotThisCircGenClass,
           Other_ThisCircGenClass = sum(ThisRepeat_ThisCircGenClass)-ThisRepeat_ThisCircGenClass) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    mapply(col.fisher.test, 
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_ThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_ThisCircGenClass,
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_NotThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_NotThisCircGenClass)
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    p.adjust(union_bkp_repeats_circlegenomeclass_vs_rest$pval, method="BH")
  
  # calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    mutate(FC = (0.00001 + (1+ThisRepeat_ThisCircGenClass) / (1+sum(ThisRepeat_ThisCircGenClass))) / (0.00001 + (1+ThisRepeat_NotThisCircGenClass) / (1+sum(ThisRepeat_NotThisCircGenClass))))
  
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>%
    mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
    scale_x_log10() +
    geom_point(size=0.5) +
    geom_text_repel(label=ifelse(union_bkp_repeats_circlegenomeclass_vs_rest$VolcanoColor != "grey", as.character(union_bkp_repeats_circlegenomeclass_vs_rest$Repeat), NA), 
                    size=2.5) +
    scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
    theme_kons1() +
    xlab(paste0("Fold Change \n Depleted <> Enriched")) + 
    ylab("-log10(p-value)") +
    guides(color=F) + 
    geom_vline(xintercept=1, linetype="dashed") + 
    geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
    ggtitle(paste0("Repeat \n Enrichment in ", thiscirclegenomeclass, " (Circle-seq Circles)")) + 
    ggsave(paste0("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_CircleSeqCircles_", thiscirclegenomeclass, "_vs_other_Repeat_Volcano.pdf"), height=4, width=5)
  
  
  ## Repeat Class
  
  union_bkp_repeats_circlegenomeclass_vs_rest = 
    union_bkp_gr %>% as_tibble() %>% 
    filter(!is.na(CircleSeqCircles_CircleGenomeClass)) %>% 
    mutate(isInThisCircleGenomeClass = as.factor(ifelse(CircleSeqCircles_CircleGenomeClass == thiscirclegenomeclass, "this_circle_genome_class", "not_this_circle_genome_class"))) %>% 
    mutate(RepeatClass=droplevels(forcats::fct_explicit_na(RepeatClass, na_level="NoRepeat"))) %>% 
    group_by(RepeatClass, isInThisCircleGenomeClass) %>% 
    summarise(nTx = n_distinct(SampleChrPos)) %>%
    ungroup() %>% 
    tidyr::complete(RepeatClass, isInThisCircleGenomeClass, fill=list(nTx=0)) %>% 
    spread(isInThisCircleGenomeClass, nTx) %>% 
    dplyr::rename(ThisRepeat_NotThisCircGenClass = not_this_circle_genome_class,
                  ThisRepeat_ThisCircGenClass = this_circle_genome_class) %>% 
    mutate(Other_NotThisCircGenClass = sum(ThisRepeat_NotThisCircGenClass)-ThisRepeat_NotThisCircGenClass,
           Other_ThisCircGenClass = sum(ThisRepeat_ThisCircGenClass)-ThisRepeat_ThisCircGenClass) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    mapply(col.fisher.test, 
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_ThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_ThisCircGenClass,
           union_bkp_repeats_circlegenomeclass_vs_rest$ThisRepeat_NotThisCircGenClass, union_bkp_repeats_circlegenomeclass_vs_rest$Other_NotThisCircGenClass)
  union_bkp_repeats_circlegenomeclass_vs_rest$pval = 
    p.adjust(union_bkp_repeats_circlegenomeclass_vs_rest$pval, method="BH")
  
  # calculate FC (proportion of palmtree tx in this repeat vs. proportion of nonpalmtree tx in this repeat)
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    mutate(FC = (0.00001 + (1+ThisRepeat_ThisCircGenClass) / (1+sum(ThisRepeat_ThisCircGenClass))) / (0.00001 + (1+ThisRepeat_NotThisCircGenClass) / (1+sum(ThisRepeat_NotThisCircGenClass))))
  
  union_bkp_repeats_circlegenomeclass_vs_rest = union_bkp_repeats_circlegenomeclass_vs_rest %>%
    mutate(VolcanoColor = ifelse(pval>0.05, "grey", ifelse(FC<1, "blue", "red"))) 
  
  union_bkp_repeats_circlegenomeclass_vs_rest %>% 
    ggplot(aes(x=FC, y=-log10(pval), color=VolcanoColor)) + 
    scale_x_log10() +
    geom_point(size=0.5) +
    geom_text_repel(label=ifelse(union_bkp_repeats_circlegenomeclass_vs_rest$VolcanoColor != "grey", as.character(union_bkp_repeats_circlegenomeclass_vs_rest$RepeatClass), NA), 
                    size=2.5) +
    scale_color_manual(values=c("grey" = "gray50", "blue"="steelblue", "red"="firebrick2"))+
    theme_kons1() +
    xlab(paste0("Fold Change \n Depleted <> Enriched")) + 
    ylab("-log10(p-value)") +
    guides(color=F) + 
    geom_vline(xintercept=1, linetype="dashed") + 
    geom_hline(yintercept=-log10(0.05), linetype="dashed") + 
    ggtitle(paste0("Repeat Class \n Enrichment in ", thiscirclegenomeclass, " (Circle-seq circles)")) + 
    ggsave(paste0("~/Desktop/PalmTrees/Results/Figures/Repeats/Union_CircleSeqCircles_", thiscirclegenomeclass, "_vs_other_RepeatClass_Volcano.pdf"), height=4, width=5)
}








